E-visa/Controllers/VisaController.cs
using AutoMapper;
using E_Visa.Data;
using E_Visa.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
using Xceed.Document.NET;
using Xceed.Words.NET;

namespace E_Visa.Controllers
{
    [Authorize]
    public class VisaController : Controller
    {
        private readonly EvisaDbContext _context;
        public VisaController(EvisaDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        [Consumes("multipart/form-data")]
        [HttpPost]
        public async Task<ActionResult<EvisaForm>> PostApplicationForm([FromForm] EvisaFormVM _profile)
        {
            var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            if (userId == null)
            {
                return Unauthorized();
            }

                var profile = new EvisaForm
                {
                    SurName = _profile.SurName,
                    GivenName = _profile.GivenName,
                    VisaType = _profile.VisaType,
                    Gender = _profile.Gender,
                    DateOfBirth = _profile.DateOfBirth,
                    PlaceOfBirth = _profile.PlaceOfBirth,
                    Nationality = _profile.Nationality,
                    ResidentialAddress = _profile.ResidentialAddress,
                    PhoneNumber = _profile.PhoneNumber,
                    Email = _profile.Email,
                    Religion = _profile.Religion,
                    Occupation = _profile.Occupation,
                    OccupationCompanyAddress = _profile.OccupationCompanyAddress,
                    OccupationCompanyName = _profile.OccupationCompanyName,
                    PassportNumber = _profile.PassportNumber,
                    PassportType = _profile.PassportType,
                    PlaceIssue = _profile.PlaceIssue,
                    IntendedArrivalDate = _profile.IntendedArrivalDate,
                    PassportIssueDate = _profile.PassportIssueDate,
                    PassportExpiryDate = _profile.PassportExpiryDate,
                    OtherPassport = _profile.OtherPassport,
                    PassportOtherNo = _profile.PassportOtherNo,
                    PlaceOtherIssue = _profile.PlaceOtherIssue,
                    OtherIssueDate = _profile.OtherIssueDate,
                    OtherIssueExpiryDate = _profile.OtherIssueExpiryDate,
                    BeenToVietNam = _profile.BeenToVietNam,
                    PassportBeenToVietNamNo = _profile.PassportBeenToVietNamNo,
                    BeenToVietNamFullName = _profile.BeenToVietNamFullName,
                    BeenToVietNamDateOfBirth = _profile.BeenToVietNamDateOfBirth,
                    BeenToVietNamNationality = _profile.BeenToVietNamNationality,
                    MultipleNationality = _profile.MultipleNationality,
                    EnterOtherNationality = _profile.EnterOtherNationality,
                    VisitedVietNam = _profile.VisitedVietNam,
                    VisitedVietNamFrom = _profile.VisitedVietNamFrom,
                    VisitedVietNamTo = _profile.VisitedVietNamTo,
                    VisitedVietNamPurpose = _profile.VisitedVietNamPurpose,
                    LengthOfStay = _profile.LengthOfStay,
                    PurposeOfVisit = _profile.PurposeOfVisit,
                    IntendedAddress = _profile.IntendedAddress,
                    GrantEvisa = _profile.GrantEvisa,
                    GrantEvisaTo = _profile.GrantEvisaTo,
                    EntryGate = _profile.EntryGate,
                    ExitGate = _profile.ExitGate,
                    IntendedExpenses = _profile.IntendedExpenses,
                    ExpensesBy = _profile.ExpensesBy,
                    HealthInsurance = _profile.HealthInsurance,
                    AppUserId = userId,
                    PortraitFormat = await ConvertImageBase.ImageToBase64(_profile.PortraitFormatImage),
                    PassportFrontPage = await ConvertImageBase.ImageToBase64(_profile.PassportFrontPageImage),
                };

                await _context.EvisaForm.AddAsync(profile);
                await _context.SaveChangesAsync();

            return RedirectToAction("FormHistory");
        }

        public async Task<ActionResult> FormHistory()
        {
            var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            if (userId == null)
            {
                return Unauthorized();
            }

            var profile = await _context.EvisaForm
                .Where(e => e.AppUserId == userId)
                .OrderByDescending(e => e.Id) 
                .ToListAsync();

            if (profile == null)
            {
                return NotFound();
            }

            return View(profile);
        }

        [HttpGet]
        public async Task<IActionResult> DetailsForm(int id)
        {
            var profile = await _context.EvisaForm.FindAsync(id);

            if (profile == null)
            {
                return NotFound();
            }

            return View(profile);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var profile = await _context.EvisaForm.FindAsync(id);

            if (profile == null)
            {
                return NotFound();
            }

            _context.EvisaForm.Remove(profile);
            await _context.SaveChangesAsync();

            return RedirectToAction("FormHistory"); 
        }

        [HttpGet]
        public async Task<IActionResult> EditApplicationForm(int id)
        {
            var profile = await _context.EvisaForm.FindAsync(id);

            if (profile == null)
            {
                return NotFound();
            }

            return View(profile);
        }

        [HttpPost]
        public async Task<IActionResult> EditApplicationForm([FromRoute] int id, [FromForm] EvisaFormVM _profile)
        {
            var profile = await _context.EvisaForm.FindAsync(id);
            if (profile == null)
            {
                return NotFound();
            }
            if (_profile.MultipleNationality == 1)
            {
                _profile.EnterOtherNationality = "";
            }
            if (_profile.OtherPassport == 1)
            {
                _profile.PassportOtherNo = "";
                _profile.PlaceOtherIssue = "";
                _profile.OtherIssueDate = "";
                _profile.OtherIssueExpiryDate = "";
            }
            if (_profile.BeenToVietNam == 1)
            {
                _profile.PassportBeenToVietNamNo = "";
                _profile.BeenToVietNamFullName = "";
                _profile.BeenToVietNamDateOfBirth = "";
                _profile.BeenToVietNamNationality = "";
            }
            if (_profile.VisitedVietNam == 1)
            {
                _profile.VisitedVietNamFrom = "";
                _profile.VisitedVietNamTo = "";
                _profile.VisitedVietNamPurpose = "";
            }

            profile.SurName = _profile.SurName;
            profile.GivenName = _profile.GivenName;
            profile.VisaType = _profile.VisaType;
            profile.Gender = _profile.Gender;
            profile.DateOfBirth = _profile.DateOfBirth;
            profile.PlaceOfBirth = _profile.PlaceOfBirth;
            profile.Nationality = _profile.Nationality;
            profile.ResidentialAddress = _profile.ResidentialAddress;
            profile.PhoneNumber = _profile.PhoneNumber;
            profile.Email = _profile.Email;
            profile.Religion = _profile.Religion;
            profile.Occupation = _profile.Occupation;
            profile.OccupationCompanyAddress = _profile.OccupationCompanyAddress;
            profile.OccupationCompanyName = _profile.OccupationCompanyName;
            profile.PassportNumber = _profile.PassportNumber;
            profile.PassportType = _profile.PassportType;
            profile.PlaceIssue = _profile.PlaceIssue;
            profile.IntendedArrivalDate = _profile.IntendedArrivalDate;
            profile.PassportIssueDate = _profile.PassportIssueDate;
            profile.PassportExpiryDate = _profile.PassportExpiryDate;
            profile.OtherPassport = _profile.OtherPassport;
            profile.PassportOtherNo = _profile.PassportOtherNo;
            profile.PlaceOtherIssue = _profile.PlaceOtherIssue;
            profile.OtherIssueDate = _profile.OtherIssueDate;
            profile.OtherIssueExpiryDate = _profile.OtherIssueExpiryDate;
            profile.BeenToVietNam = _profile.BeenToVietNam;
            profile.PassportBeenToVietNamNo = _profile.PassportBeenToVietNamNo;
            profile.BeenToVietNamFullName = _profile.BeenToVietNamFullName;
            profile.BeenToVietNamDateOfBirth = _profile.BeenToVietNamDateOfBirth;
            profile.BeenToVietNamNationality = _profile.BeenToVietNamNationality;
            profile.MultipleNationality = _profile.MultipleNationality;
            profile.EnterOtherNationality = _profile.EnterOtherNationality;
            profile.VisitedVietNam = _profile.VisitedVietNam;
            profile.VisitedVietNamFrom = _profile.VisitedVietNamFrom;
            profile.VisitedVietNamTo = _profile.VisitedVietNamTo;
            profile.VisitedVietNamPurpose = _profile.VisitedVietNamPurpose;
            profile.LengthOfStay = _profile.LengthOfStay;
            profile.PurposeOfVisit = _profile.PurposeOfVisit;
            profile.IntendedAddress = _profile.IntendedAddress;
            profile.GrantEvisa = _profile.GrantEvisa;
            profile.GrantEvisaTo = _profile.GrantEvisaTo;
            profile.EntryGate = _profile.EntryGate;
            profile.ExitGate = _profile.ExitGate;
            profile.IntendedExpenses = _profile.IntendedExpenses;
            profile.ExpensesBy = _profile.ExpensesBy;

E-visa/Views/Visa/Done.cshtml
@model E_Visa.Models.EvisaForm
<div class="finish">
    <h2 class="text text-center">
        <strong>FINISHED</strong>
    </h2>
    <p>
        Your application has been successfully completed. A reference number has been sent to your email address.
    </p>
    <p>
        In some cases, e-mail messages may be classified as "junk" or "spam" messages and automatically sent to these folders.
    </p>
    <p>
        If you did not receive the email you requested, please check your spam or record your information as below to check the Payment Status,
        Resend payment, Edit profile, Print receipt, Approve eVisa application status or Download eVisa certificate before submitting a new request. gica com
    </p>
    <p>
        Dowload receipt: 
        <a asp-action="PrintForm" asp-controller="Visa" asp-route-id="@Model.Id" target="_blank">
            Print to Word
        </a>
    </p>
</div>

E-visa/Views/Visa/FormHistory.cshtml
@model List<E_Visa.Models.EvisaForm>
<style>
    .table thead tr th {
        text-align: center
    }

    .table tbody tr td {
        text-align: center
    }
</style>
<h2>Registration Form History</h2>

@if (Model.Count > 0)
{
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Surname</th>
                <th>Given Name</th>
                <th>Type of Visa</th>
                <th>Nationality</th>
                <th>Email</th>
                <th>Phone Number</th>
                <th>Option</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var profile in Model)
            {
                <tr>
                    <td>@profile.Id</td>
                    <td>@profile.SurName</td>
                    <td>@profile.GivenName</td>
                    <td>
                        @switch (profile.VisaType)
                        {
                            case VisaType.SingleEntryVisa:
                                <text>Single entry visa</text>
                                break;
                            case VisaType.MultipleEntryVisa:
                                <text>Multiple entry visa</text>
                                break;
                            default:
                                <text>Không xác định</text>
                                break;
                        }
                    </td>
                    <td>@profile.Nationality</td>
                    <td>@profile.Email</td>
                    <td>@profile.PhoneNumber</td>
                    <td>
                        <a asp-action="DetailsForm" asp-controller="Visa" asp-route-id="@profile.Id" class="btn btn-outline-primary btn-sm" title="View details">
                            <i class="fa-regular fa-eye"></i>
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>No registration form available. <a style="text-decoration: none" asp-action="Index" asp-controller="Visa">Click here</a> to register your first form</p>
}

E-visa/Views/Visa/Payment.cshtml
<div class="visa-personal-infor">
    <div class="row">
        <div class="col-12 infor-banner">
            Tri chả
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-4 mb-lg-0 mb-3">
                    <div class="card p-3">
                        <div class="img-box">
                            <img src="https://www.freepnglogos.com/uploads/visa-logo-download-png-21.png" alt="">
                        </div>
                        <div class="number">
                            <label class="fw-bold" for="">**** **** **** 1060</label>
                        </div>
                        <div class="d-flex align-items-center justify-content-between">
                            <small><span class="fw-bold">Expiry date:</span><span>10/16</span></small>
                            <small><span class="fw-bold">Name:</span><span>Kumar</span></small>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 mb-lg-0 mb-3">
                    <div class="card p-3">
                        <div class="img-box">
                            <img src="https://www.freepnglogos.com/uploads/mastercard-png/file-mastercard-logo-svg-wikimedia-commons-4.png"
                                 alt="">
                        </div>
                        <div class="number">
                            <label class="fw-bold">**** **** **** 1060</label>
                        </div>
                        <div class="d-flex align-items-center justify-content-between">
                            <small><span class="fw-bold">Expiry date:</span><span>10/16</span></small>
                            <small><span class="fw-bold">Name:</span><span>Kumar</span></small>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 mb-lg-0 mb-3">
                    <div class="card p-3">
                        <div class="img-box">
                            <img src="https://www.freepnglogos.com/uploads/discover-png-logo/credit-cards-discover-png-logo-4.png"
                                 alt="">
                        </div>
                        <div class="number">
                            <label class="fw-bold">**** **** **** 1060</label>
                        </div>
                        <div class="d-flex align-items-center justify-content-between">
                            <small><span class="fw-bold">Expiry date:</span><span>10/16</span></small>
                            <small><span class="fw-bold">Name:</span><span>Kumar</span></small>
                        </div>
                    </div>
                </div>
                <div class="col-12 mt-4">
                    <div class="card p-3">
                        <p class="mb-0 fw-bold h4">Payment Methods</p>
                    </div>
                </div>
                <div class="col-12">
                    <div class="card p-3">
                        <div class="card-body border p-0">
                            <p>
                                <a class="btn btn-primary w-100 h-100 d-flex align-items-center justify-content-between"
                                   data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="true"
                                   aria-controls="collapseExample">
                                    <span class="fw-bold">PayPal</span>
                                    <span class="fab fa-cc-paypal">
                                    </span>
                                </a>
                            </p>
                            <div class="collapse p-3 pt-0" id="collapseExample">
                                <div class="row">
                                    <div class="col-8">
                                        <p class="h4 mb-0">Summary</p>
                                        <p class="mb-0">
                                            <span class="fw-bold">Product:</span><span class="c-green">
                                                : Name of
                                                product
                                            </span>
                                        </p>
                                        <p class="mb-0">
                                            <span class="fw-bold">Price:</span><span class="c-green">:$452.90</span>
                                        </p>
                                        <p class="mb-0">
                                            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Atque
                                            nihil neque
                                            quisquam aut
                                            repellendus, dicta vero? Animi dicta cupiditate, facilis provident quibusdam ab
                                            quis,
                                            iste harum ipsum hic, nemo qui!
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="card-body border p-0">
                            <p>
                                <a class="btn btn-primary p-2 w-100 h-100 d-flex align-items-center justify-content-between"
                                   data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="true"
                                   aria-controls="collapseExample">
                                    <span class="fw-bold">Credit Card</span>
                                    <span class="">
                                        <span class="fab fa-cc-amex"></span>
                                        <span class="fab fa-cc-mastercard"></span>
                                        <span class="fab fa-cc-discover"></span>
                                    </span>
                                </a>
                            </p>
                            <div class="collapse show p-3 pt-0" id="collapseExample">
                                <div class="row">
                                    <div class="col-lg-5 mb-lg-0 mb-3">
                                        <p class="h4 mb-0">Summary</p>
                                        <p class="mb-0">
                                            <span class="fw-bold">Product:</span><span class="c-green">
                                                : Name of
                                                product
                                            </span>
                                        </p>
                                        <p class="mb-0">
                                            <span class="fw-bold">Price:</span>
                                            <span class="c-green">:$452.90</span>
                                        </p>
                                        <p class="mb-0">
                                            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Atque
                                            nihil neque
                                            quisquam aut
                                            repellendus, dicta vero? Animi dicta cupiditate, facilis provident quibusdam ab
                                            quis,
                                            iste harum ipsum hic, nemo qui!
                                        </p>
                                    </div>
                                    <div class="col-lg-7">

                                        <div class="row">
                                            <div class="col-12">
                                                <div class="form__div">
                                                    <input type="text" class="form-control" placeholder=" ">
                                                    <label for="" class="form__label">Card Number</label>
                                                </div>
                                            </div>

                                            <div class="col-6">
                                                <div class="form__div">
                                                    <input type="text" class="form-control" placeholder=" ">
                                                    <label for="" class="form__label">MM / yy</label>
                                                </div>
                                            </div>

                                            <div class="col-6">
                                                <div class="form__div">
                                                    <input type="password" class="form-control" placeholder=" ">
                                                    <label for="" class="form__label">cvv code</label>
                                                </div>
                                            </div>
                                            <div class="col-12">
                                                <div class="form__div">
                                                    <input type="text" class="form-control" placeholder=" ">
                                                    <label for="" class="form__label">name on the card</label>
                                                </div>
                                            </div>
                                            <div class="col-12">
                                                <a asp-action="Done" asp-route-id="@Model.Id" asp-controller="Visa" class="btn btn-primary w-100">
                                                    <i class="fa-brands fa-cc-visa"></i> Payment
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>